import os
from dotenv import load_dotenv
load_dotenv()

cMN = os.getenv("CLAUDE_MODEL_NAME")
cAK = os.getenv("CLAUDE_API_KEY")

import anthropic
client = anthropic.Anthropic(api_key=cAK)

#USE THE CODE EXECUTION TOOL
# response = client.messages.create(
#     model=cMN,
#     max_tokens=800 ,
#     messages=[
#         {
#             "role": "user",
#             "content": "Use the code execution tool to calculate the mean and standard deviation of [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]",
#         }
#     ],
#     tools=[{"type": "code_execution_20260521", "name": "code_execution"}],
# )

# for block in response.content:
#     if block.type == "text":
#         print(block.text)


# #INSPECT THE ENTIRE API RESPONSE FOR CODE EXECUTION USAGE
# print(response.to_json())





#UPLOAD FILE FOR ANALYSIS
from pathlib import Path

file_object = client.files.upload(file=Path("./marketing_campaigns.csv"))

#PROMPT CLAUDE FOR ANALYSIS
user_prompt = """You are a senior marketing data analyst.

Analyze the attached marketing_campaigns.csv dataset using Python.

Generate a Matplotlib bar chart showing the total revenue generated by each marketing channel.

Then:

- Identify the highest-performing marketing channel.
- Calculate the average ROAS for each channel.
- Summarize your findings in a few bullet points.

Use Python code execution for all calculations and visualizations."""

# Use the file_id with code execution
response = client.messages.create(
    model=cMN,
    #betas=["files-api-2025-04-14"],
    max_tokens=888,
    messages=[
        {
            "role": "user",
            "content": [
                {"type": "text", "text": user_prompt},
                {"type": "container_upload", "file_id": file_object.id},
            ],
        }
    ],
    tools=[{"type": "code_execution_20260521", "name": "code_execution"}],
)

# display the text-based assistant response
print("===> ",response,"<===")
for block in response.content:
    if block.type == "text":
        print(block.text)


#RETRIEVE GENERATED FILES
from anthropic.types import Message

# Extract file IDs from the response
def extract_file_ids(response: Message) -> list[str]:
    file_ids: list[str] = []
    for item in response.content:
        if item.type == "bash_code_execution_tool_result":
            content_item = item.content
            if content_item.type == "bash_code_execution_result":
                for output_block in content_item.content:
                    file_ids.append(output_block.file_id)
    return file_ids


# Download the created files
for file_id in extract_file_ids(response):
    file_metadata = client.files.retrieve_metadata(file_id)
    file_content = client.files.download(file_id)
    file_content.write_to_file(file_metadata.filename)
    print(f"Downloaded: {file_metadata.filename}")

























    ###
# For the dataset **[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]**:

# - **Mean**: 5.5
# - **Standard Deviation**:
#   - Population (÷N): **≈ 2.8723**
#   - Sample (÷N-1): **≈ 3.0277**

# The sample standard deviation is typically used when the data represents a sample from a larger population, while the population standard deviation is used when the data represents the entire population.
# {
#   "id": "msg_011CfJXeC7hCBJ4Gu2mckfTV",
#   "container": {
#     "id": "container_012mga5TekRTrhNQUwCgJmmT",
#     "expires_at": "2026-09-22T14:07:24.969390Z"
#   },
#   "content": [
#     {
#       "id": "srvtoolu_012qbgF5ugPPxdp3b2AJh3pR",
#       "input": {
#         "command": "python3 -c \"\nimport statistics as s\ndata = [1,2,3,4,5,6,7,8,9,10]\nmean = s.mean(data)\npstdev = s.pstdev(data)\nstdev = s.stdev(data)\nprint('Mean:', mean)\nprint('Population Std Dev:', pstdev)\nprint('Sample Std Dev:', stdev)\n\"\n"
#       },
#       "name": "bash_code_execution",
#       "type": "server_tool_use"
#     },
#     {
#       "content": {
#         "content": [],
#         "return_code": 0,
#         "stderr": "",
#         "stdout": "Mean: 5.5\nPopulation Std Dev: 2.8722813232690143\nSample Std Dev: 3.0276503540974917\n",
#         "type": "bash_code_execution_result"
#       },
#       "tool_use_id": "srvtoolu_012qbgF5ugPPxdp3b2AJh3pR",
#       "type": "bash_code_execution_tool_result"
#     },
#     {
#       "text": "For the dataset **[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]**:\n\n- **Mean**: 5.5\n- **Standard Deviation**:\n  - Population (÷N): **≈ 2.8723**\n  - Sample (÷N-1): **≈ 3.0277**\n\nThe sample standard deviation is typically used when the data represents a sample from a larger population, while the population standard deviation is used when the data represents the entire population.",
#       "type": "text"
#     }
#   ],
#   "model": "claude-sonnet-5",
#   "role": "assistant",
#   "stop_details": null,
#   "stop_reason": "end_turn",
#   "stop_sequence": null,
#   "type": "message",
#   "usage": {
#     "cache_creation": {
#       "ephemeral_1h_input_tokens": 0,
#       "ephemeral_5m_input_tokens": 0
#     },
#     "cache_creation_input_tokens": 0,
#     "cache_read_input_tokens": 0,
#     "inference_geo": "global",
#     "input_tokens": 6201,
#     "output_tokens": 328,
#     "output_tokens_details": {
#       "thinking_tokens": 0
#     },
#     "server_tool_use": {
#       "web_fetch_requests": 0,
#       "web_search_requests": 0
#     },
#     "service_tier": "standard"
#   }
# }

###

# ===>  Message(id='msg_011CfJp9ecaDRQDcSjBKTxX9', container=Container(id='container_01KL3bCare4StYuTSnX2xP7q', expires_at=datetime.datetime(2026, 9, 22, 17, 44, 23, 598722, tzinfo=TzInfo(0)), skills=None), content=[ThinkingBlock(signature='EpACCpABCBIYAipAUE4c3o/pkoMJaI9LbukhUIKT84SeHTAGaDg+6N/hh2c2RSbRkdW8itKzY6nhrwmILP8pKkT6VobXmNEZjTII8DIPY2xhdWRlLXNvbm5ldC01OABCCHRoaW5raW5nWiQ2NjcwOTQ0NC0xMmQ3LTRjOWEtYWQyNi1jYjhmMTI3ZTRjYTGoAcbgytUGEgxDtQ7OIn4gC+So/B8aDBhRALMhNVyzkRfpNCIw0CeTPA+DnTmVnCYDSUn3P73Qjy1Y+1/xI1dQL+PqFj3T7Nu3E9gmo1MIepTVOWLzKi310tY28oNTY+XBHqlyoHFl66m100YUjWs5yxxbLsCvfoM/3EdIrj4E1+znweMYAQ==', thinking='', type='thinking'), ServerToolUseBlock(id='srvtoolu_0123fNcC6SN7Wjz5ZbSPNETq', caller=None, input={'command': 'cd "$INPUT_DIR" && ls -la && echo "---" && head -20 marketing_campaigns.csv && echo "---" && wc -l marketing_campaigns.csv'}, name='bash_code_execution', type='server_tool_use'), BashCodeExecutionToolResultBlock(content=BashCodeExecutionResultBlock(content=[], return_code=0, stderr='', stdout='total 12\ndrwxr-xr-x 2 root root 4096 Sep 22 16:43 .\ndrwxr-xr-x 3 root root 4096 Sep 22 16:43 ..\n-rw-r--r-- 1 root root 1865 Sep 22 16:43 marketing_campaigns.csv\n---\nCampaign_ID,Campaign_Name,Channel,Region,Month,Impressions,Clicks,CTR,Conversions,Conversion_Rate,Spend_USD,Revenue_USD,ROAS\nMC001,Summer Sale,Google Ads,North America,January,125000,4200,3.36,210,5.00,4800,18600,3.88\nMC002,Summer Sale,Facebook Ads,Europe,January,98000,2850,2.91,142,4.98,3600,10950,3.04\nMC003,Product Launch,LinkedIn,Asia,January,42000,1450,3.45,88,6.07,2400,12400,5.17\nMC004,Brand Awareness,Instagram,North America,February,182000,5400,2.97,175,3.24,6200,15800,2.55\nMC005,Retargeting,Google Ads,Europe,February,68000,3950,5.81,330,8.35,4100,27200,6.63\nMC006,Lead Generation,LinkedIn,Australia,February,36000,1220,3.39,94,7.70,1900,9800,5.16\nMC007,Spring Promo,Facebook Ads,Asia,March,118000,3400,2.88,180,5.29,4200,16800,4.00\nMC008,Email Campaign,Email,North America,March,54000,6100,11.30,560,9.18,900,31500,35.00\nMC009,Product Launch,Google Ads,Europe,March,145000,5200,3.59,320,6.15,5700,28400,4.98\nMC010,Webinar Promotion,LinkedIn,North America,April,39000,1680,4.31,155,9.23,2300,14900,6.48\nMC011,Summer Sale,Instagram,Asia,April,161000,4820,2.99,240,4.98,5100,19700,3.86\nMC012,Retargeting,Google Ads,Australia,April,74000,4520,6.11,410,9.07,4300,34800,8.09\nMC013,Email Campaign,Email,Europe,May,49000,5500,11.22,510,9.27,850,28900,34.00\nMC014,Lead Generation,Facebook Ads,North America,May,99000,3100,3.13,165,5.32,3400,14100,4.15\nMC015,Brand Awareness,Instagram,Europe,May,205000,5980,2.92,210,3.51,7100,18100,2.55\nMC016,Product Launch,Google Ads,Asia,June,151000,5610,3.72,355,6.33,5900,32700,5.54\nMC017,Webinar Promotion,LinkedIn,Europe,June,47000,1930,4.11,188,9.74,2400,17300,7.21\nMC018,Email Campaign,Email,Asia,June,58000,6420,11.07,590,9.19,950,34400,36.21\nMC019,Retargeting,Google Ads,North America,July,81000,5010,6.19,470,9.38,4600,38100,8.28\n---\n20 marketing_campaigns.csv\n', type='bash_code_execution_result'), tool_use_id='srvtoolu_0123fNcC6SN7Wjz5ZbSPNETq', type='bash_code_execution_tool_result'), ServerToolUseBlock(id='srvtoolu_01LXLmaYe1UwzCNMn7CAcks8', caller=None, input={'command': 'mkdir -p /tmp/out && cat << \'EOF\' > /tmp/analyze.py\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv("/tmp/marketing_campaigns.csv") if False else None\nEOF\ncp "$INPUT_DIR/marketing_campaigns.csv" /tmp/marketing_campaigns.csv\necho done'}, name='bash_code_execution', type='server_tool_use'), BashCodeExecutionToolResultBlock(content=BashCodeExecutionResultBlock(content=[], return_code=0, stderr='', stdout='done\n', type='bash_code_execution_result'), tool_use_id='srvtoolu_01LXLmaYe1UwzCNMn7CAcks8', type='bash_code_execution_tool_result'), ServerToolUseBlock(id='srvtoolu_01DSSLrUov7ddnmQXcfrE3jN', caller=None, input={'command': 'create', 'path': '/tmp/analyze.py', 'file_text': 'import pandas as pd\nimport matplotlib.pyplot as plt\n\n# Load data\ndf = pd.read_csv("/tmp/marketing_campaigns.csv")\n\nprint("=== Basic Info ===")\nprint(df.shape)\nprint(df.dtypes)\nprint(df.head())\n\n# --- Aggregations ---\nrevenue_by_channel = df.groupby("Channel")["Revenue_USD"].sum().sort_values(ascending=False)\nspend_by_channel = df.groupby("Channel")["Spend_USD"].sum()\navg_roas_by_channel = df.groupby("Channel")["ROAS"].mean().sort_values(ascending=False)\n\nprint("\\n=== Total Revenue by Channel ===")\nprint(revenue_by_channel)\n\nprint("\\n=== Total Spend by Channel ===")\nprint(spend_by_channel)\n\nprint("\\n=== Average ROAS by Channel ===")\nprint(avg_roas_by_channel)\n\n# Overall best channel by revenue\ntop_channel_revenue = revenue_by_channel.idxmax()\ntop_channel_revenue_val = revenue_by_channel.max()\n\n# Overall best channel by ROAS\ntop_channel_roas = avg_roas_by_channel.idxmax()\ntop_channel_roas_val = avg_roas_by_channel.max()\n\nprint(f"\\nHighest revenue-generating channel: {top_channel_revenue} (${top_channel_revenue_val:,.0f})")\nprint(f"Highest average ROAS channel: {top_channel_roas} ({top_channel_roas_val:.2f}x)")\n\n# --- Chart ---\nplt.figure(figsize=(9,6))\ncolors = plt.cm.viridis_r([i/len(revenue_by_channel) for i in range(len(revenue_by_channel))])\nbars = plt.bar(revenue_by_channel.index, revenue_by_channel.values, color=colors, edgecolor=\'black\')\n\n# Highlight the top channel\nfor bar, channel in zip(bars, revenue_by_channel.index):\n    if channel == top_channel_revenue:\n        bar.set_color(\'#d62728\')\n        bar.set_edgecolor(\'black\')\n        bar.set_linewidth(1.5)\n\nplt.title("Total Revenue by Marketing Channel", fontsize=14, fontweight=\'bold\')\nplt.xlabel("Marketing Channel", fontsize=12)\nplt.ylabel("Total Revenue (USD)", fontsize=12)\nplt.xticks(rotation=30, ha=\'right\')\n\n# Add value labels on top of bars\nfor i, v in enumerate(revenue_by_channel.values):\n    plt.text(i, v + max(revenue_by_channel.values)*0.01, f"${v:,.0f}", ha=\'center\', va=\'bottom\', fontsize=9)\n\nplt.tight_layout()\nplt.savefig("/tmp/out/revenue_by_channel.png", dpi=150)\nplt.close()\n\nprint("\\nChart saved to /tmp/out/revenue_by_channel.png")\n\n# Save summary table too\nsummary = pd.DataFrame({\n    "Total_Revenue_USD": revenue_by_channel,\n    "Total_Spend_USD": spend_by_channel,\n    "Avg_ROAS": avg_roas_by_channel\n}).sort_values("Total_Revenue_USD", ascending=False)\nsummary["Overall_ROAS (Rev/Spend)"] = summary["Total_Revenue_USD"] / summary["Total_Spend_USD"]\nprint("\\n=== Summary Table ===")\nprint(summary.round(2))\nsummary.round(2).to_csv("/tmp/out/channel_summary.csv")\n'}, name='text_editor_code_execution', type='server_tool_use'), TextEditorCodeExecutionToolResultBlock(content=TextEditorCodeExecutionToolResultError(error_code='unavailable', error_message='Tool response parsing error for create: Failed to parse tool response as JSON: unexpected character: line 1 column 1 (char 0)', type='text_editor_code_execution_tool_result_error'), tool_use_id='srvtoolu_01DSSLrUov7ddnmQXcfrE3jN', type='text_editor_code_execution_tool_result'), ThinkingBlock(signature='EvkBCpABCBIYAipAGuXnEui+7tK6jlYEB4OBY6DfhXBq4ovVgpFBp0naHbE2WcSummIP7TqfAnce8eCaG63AJaf4fqVpmcQkQCFmHDIPY2xhdWRlLXNvbm5ldC01OABCCHRoaW5raW5nWiQ2NjcwOTQ0NC0xMmQ3LTRjOWEtYWQyNi1jYjhmMTI3ZTRjYTGoAdfgytUGEgzM26d/9A8ldnKJhrsaDPQhRlbWci8/SyxjiCIwQkUjMVq3o1OV/QIsDWbO7c67UdvFUXUIb4HxeJHGQmPi7ZYdaAhNSuMDLLyA3ZE1KhaTj+FYtZeymc8AtJsrdVDm6l0Mbh2dGAE=', thinking='', type='thinking'), ServerToolUseBlock(id='srvtoolu_01Lb3L1JR7LFJQPMGojGqSLv', caller=None, input={'command': 'mkdir -p /tmp/out\ncat << \'PYEOF\' > /tmp/analyze.py\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv("/tmp/marketing_campaigns.csv")\n\nprint("=== Basic Info ===")\nprint(df.shape)\nprint(df.dtypes)\nprint(df.head())\n\nrevenue_by_channel = df.groupby("Channel")["Revenue_USD"].sum().sort_values(ascending=False)\nspend_by_channel = df.groupby("Channel")["Spend_USD"].sum()\navg_roas_by_channel = df.groupby("Channel")["ROAS"].mean().sort_values(ascending=False)\n\nprint("\\n=== Total Revenue by Channel ===")\nprint(revenue_by_channel)\n\nprint("\\n=== Total Spend by Channel ===")\nprint(spend_by_channel)\n\nprint("\\n=== Average ROAS by Channel ===")\nprint(avg_roas_by_channel)\n\ntop_channel_revenue = revenue_by_channel.idxmax()\ntop_channel_revenue_val = revenue_by_channel.max()\n\ntop_channel_roas = avg_roas_by_channel.idxmax()\ntop_channel_roas_val = avg_roas_by_channel.max()\n\nprint(f"\\nHighest revenue-generating channel: {top_channel_revenue} (${top_channel_revenue_val:,.0f})")\nprint(f"Highest average ROAS channel: {top_channel_roas} ({top_channel_roas_val:.2f}x)")\n\nplt.figure(figsize=(9,6))\ncolors = plt.cm.viridis_r([i/len(revenue_by_channel) for i in range(len(revenue_by_channel))])\nbars = plt.bar(revenue_by_channel.index, revenue_by_channel.values, color=colors, edgecolor=\'black\')\n\nfor bar, channel in zip(bars, revenue_by_channel.index):\n    if channel == top_channel_revenue:\n        bar.set_color(\'#d62728\')\n        bar.set_edgecolor(\'black\')\n        bar.set_linewidth(1.5)\n\nplt.title("Total Revenue by Marketing Channel", fontsize=14, fontweight=\'bold\')\nplt.xlabel("Marketing Channel", fontsize=12)\nplt.ylabel("Total Revenue (USD)", fontsize=12)\nplt.xticks(rotation=30, ha=\'right\')\n\nfor i, v in enumerate(revenue_by_channel.values):\n    plt.text(i, v + max(revenue_by_channel.values)*0.01, f"${v:,.0f}", ha=\'center\', va=\'bottom\', fontsize=9)\n\nplt.tight_layout()\nplt.savefig("/tmp/out/revenue_by_channel.png", dpi=150)\nplt.close()\n\nprint("\\nChart saved to /tmp/out/revenue_by_channel.png")\n\nsummary = pd.DataFrame({\n    "Total_Revenue_USD": revenue_by_channel,\n    "Total_Spend_USD": spend_by_channel,\n    "Avg_ROAS": avg_roas_by_channel\n}).sort_values("Total_Revenue_USD", ascending=False)\nsummary["Overall_ROAS (Rev/Spend)"] = summary["Total_Revenue_USD"] / summary["Total_Spend_USD"]\nprint("\\n=== Summary Table ===")\nprint(summary.round(2))\nsummary.round(2).to_csv("/tmp/out/channel_summary.csv")\nPYEOF\npython3 /tmp/analyze.py\n'}, name='bash_code_execution', type='server_tool_use'), BashCodeExecutionToolResultBlock(content=BashCodeExecutionResultBlock(content=[], return_code=0, stderr='', stdout='=== Basic Info ===\n(20, 13)\nCampaign_ID         object\nCampaign_Name       object\nChannel             object\nRegion              object\nMonth               object\nImpressions          int64\nClicks               int64\nCTR                float64\nConversions          int64\nConversion_Rate    float64\nSpend_USD            int64\nRevenue_USD          int64\nROAS               float64\ndtype: object\n  Campaign_ID    Campaign_Name       Channel  ... Spend_USD Revenue_USD  ROAS\n0       MC001      Summer Sale    Google Ads  ...      4800       18600  3.88\n1       MC002      Summer Sale  Facebook Ads  ...      3600       10950  3.04\n2       MC003   Product Launch      LinkedIn  ...      2400       12400  5.17\n3       MC004  Brand Awareness     Instagram  ...      6200       15800  2.55\n4       MC005      Retargeting    Google Ads  ...      4100       27200  6.63\n\n[5 rows x 13 columns]\n\n=== Total Revenue by Channel ===\nChannel\nGoogle Ads      179800\nEmail            94800\nLinkedIn         54400\nFacebook Ads     53950\nInstagram        53600\nName: Revenue_USD, dtype: int64\n\n=== Total Spend by Channel ===\nChannel\nEmail            2700\nFacebook Ads    14500\nGoogle Ads      29400\nInstagram       18400\nLinkedIn         9000\nName: Spend_USD, dtype: int64\n\n=== Average ROAS by Channel ===\nChannel\nEmail           35.070000\nGoogle Ads       6.233333\nLinkedIn         6.005000\nFacebook Ads     3.715000\nInstagram        2.986667\nName: ROAS, dtype: float64\n\nHighest revenue-generating channel: Google Ads ($179,800)\nHighest average ROAS channel: Email (35.07x)\n\nChart saved to /tmp/out/revenue_by_channel.png\n\n=== Summary Table ===\n              Total_Revenue_USD  ...  Overall_ROAS (Rev/Spend)\nChannel                          ...                          \nGoogle Ads               179800  ...                      6.12\nEmail                     94800  ...                     35.11\nLinkedIn                  54400  ...                      6.04\nFacebook Ads              53950  ...                      3.72\nInstagram                 53600  ...                      2.91\n\n[5 rows x 4 columns]\n', type='bash_code_execution_result'), tool_use_id='srvtoolu_01Lb3L1JR7LFJQPMGojGqSLv', type='bash_code_execution_tool_result'), TextBlock(citations=None, text='Analysis complete. Here are the results:', type='text'), ServerToolUseBlock(id='srvtoolu_017eZchUjFD3qvzXSkBBKevD', caller=None, input={'command': 'cp /tmp/out/revenue_by_channel.png "$OUTPUT_DIR/" && cp /tmp/out/channel_summary.csv "$OUTPUT_DIR/" && ls -la "$OUTPUT_DIR"'}, name='bash_code_execution', type='server_tool_use'), BashCodeExecutionToolResultBlock(content=BashCodeExecutionResultBlock(content=[BashCodeExecutionOutputBlock(file_id='file_011L1PkXKVEYx2eq5gwvn5dN', type='bash_code_execution_output'), BashCodeExecutionOutputBlock(file_id='file_01428j4D9ef83HqT52wgevoU', type='bash_code_execution_output')], return_code=0, stderr='', stdout='total 84\ndrwxr-xr-x 2 root root  4096 Sep 22 16:44 .\ndrwxr-xr-x 7 root root  4096 Sep 22 16:44 ..\n-rw-r--r-- 1 root root   235 Sep 22 16:44 channel_summary.csv\n-rw-r--r-- 1 root root 72996 Sep 22 16:44 revenue_by_channel.png\n', type='bash_code_execution_result'), tool_use_id='srvtoolu_017eZchUjFD3qvzXSkBBKevD', type='bash_code_execution_tool_result'), TextBlock(citations=None, text='## 📊 Marketing Channel Performance Analysis\n\nI\'ve analyzed all 20 campaigns across 5 channels (Google Ads, Email, LinkedIn, Facebook Ads, Instagram). Both the bar chart (`revenue_by_channel.png`) and summary table (`channel_summary.csv`) have been generated.\n\n### Total Revenue by Channel (highlighted chart, red = top performer)\n\n| Channel | Total Revenue | Total Spend | Avg ROAS (per-campaign) | Overall ROAS (Rev/Spend) |\n|---|---|---|---|---|\n| **Google Ads** | **$179,800** | $29,400 | 6.23x | 6.12x |\n| Email | $94,800 | $2,700 | **35.07x** | **35.11x** |\n| LinkedIn | $54,400 | $9,000 | 6.01x | 6.04x |\n| Facebook Ads | $53,950 | $14,500 | 3.72x | 3.72x |\n| Instagram | $53,600 | $18,400 | 2.99x | 2.91x |\n\n### 🏆 Key Findings\n\n- **Highest revenue generator: Google Ads** — driving **$179,800** in total revenue, nearly double the next closest channel (Email), largely due to high-volume Retargeting and Product Launch campaigns.\n- **Most efficient channel: Email** — despite generating far less revenue in absolute terms, it delivers an outstanding **~35x average ROAS**, meaning every $1 spent returns $35 in revenue — by far the most capital-efficient channel.\n- **Google Ads and LinkedIn** are the "workhorse" channels — both deliver solid, consistent ROAS in the 6x range, balancing decent scale with strong efficiency.\n- **Instagram and Facebook Ads underperform on ROAS** (≈3x and ≈3.7x respectively) despite substantial ad spend ($18.4K and $14.5K) — these channels are the least capital-efficient and may warrant budget reallocation.\n- **Strategic takeaway:** Google Ads should remain the primary scale driver for revenue, while Email marketing — despite its small spend footprint — deserves increased investment given its exceptional ROI headroom. Facebook Ads and Instagram budgets could be trimmed or optimized to improve overall marketing efficiency.\n\nBoth files (`revenue_by_channel.png` chart and `channel_summary.csv` data table) are available in the output.', type='text')], model='claude-sonnet-5', role='assistant', stop_details=None, stop_reason='end_turn', stop_sequence=None, type='message', usage=Usage(cache_creation=CacheCreation(ephemeral_1h_input_tokens=0, ephemeral_5m_input_tokens=0), cache_creation_input_tokens=0, cache_read_input_tokens=0, inference_geo='global', input_tokens=34461, output_tokens=3902, output_tokens_details=OutputTokensDetails(thinking_tokens=17), server_tool_use=ServerToolUsage(web_fetch_requests=0, web_search_requests=0), service_tier='standard')) <===
# Analysis complete. Here are the results:
# ## 📊 Marketing Channel Performance Analysis

# I've analyzed all 20 campaigns across 5 channels (Google Ads, Email, LinkedIn, Facebook Ads, Instagram). Both the bar chart (`revenue_by_channel.png`) and summary table (`channel_summary.csv`) have been generated.

# ### Total Revenue by Channel (highlighted chart, red = top performer)

# | Channel | Total Revenue | Total Spend | Avg ROAS (per-campaign) | Overall ROAS (Rev/Spend) |
# |---|---|---|---|---|
# | **Google Ads** | **$179,800** | $29,400 | 6.23x | 6.12x |
# | Email | $94,800 | $2,700 | **35.07x** | **35.11x** |
# | LinkedIn | $54,400 | $9,000 | 6.01x | 6.04x |
# | Facebook Ads | $53,950 | $14,500 | 3.72x | 3.72x |
# | Instagram | $53,600 | $18,400 | 2.99x | 2.91x |

# ### 🏆 Key Findings

# - **Highest revenue generator: Google Ads** — driving **$179,800** in total revenue, nearly double the next closest channel (Email), largely due to high-volume Retargeting and Product Launch campaigns.
# - **Most efficient channel: Email** — despite generating far less revenue in absolute terms, it delivers an outstanding **~35x average ROAS**, meaning every $1 spent returns $35 in revenue — by far the most capital-efficient channel.
# - **Google Ads and LinkedIn** are the "workhorse" channels — both deliver solid, consistent ROAS in the 6x range, balancing decent scale with strong efficiency.
# - **Instagram and Facebook Ads underperform on ROAS** (≈3x and ≈3.7x respectively) despite substantial ad spend ($18.4K and $14.5K) — these channels are the least capital-efficient and may warrant budget reallocation.
# - **Strategic takeaway:** Google Ads should remain the primary scale driver for revenue, while Email marketing — despite its small spend footprint — deserves increased investment given its exceptional ROI headroom. Facebook Ads and Instagram budgets could be trimmed or optimized to improve overall marketing efficiency.

# Both files (`revenue_by_channel.png` chart and `channel_summary.csv` data table) are available in the output.
# Downloaded: revenue_by_channel.png
# Downloaded: channel_summary.csv
